### ISSUE TITLE
Status of the adapter

### ISSUE THREAD

**Issue by lukealexmiller** [Dandandan/dbt-athena#7]
Thanks for the great work on this! 
Very keen to use dbt at our co and we're using Athena in production. 
I gave the adapter a try using `pip install dbt==1.14.0 && pip install git+https://github.com/Dandandan/dbt-athena.git`

However, running 'dbt debug' I get
`Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "athena_data_warehouse", target "awscatalog" invalid: Runtime Error
    Could not find adapter type athena!`

The profile and a project yml files have the relevant database/schema settings and pass debug.

I realise the repo does say 'work-in-progress', should this be functional right now or should I check back in on progress later.

Thanks again!

**Comment by Dandandan** [comment]
Thank you for raising the isse.

It should be functional, although still a lot of rough edges.

Can you share the structure of your project /  (with secrets removed)?

**Comment by lukealexmiller** [comment]
Hey! 
dbt_project.yml is as follows:

```
name: 'fy_analytics'
version: '1.0.0'
profile: 'athena_data_warehouse'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target" 
clean-targets: 
    - "target"
    - "dbt_modules"


models:
  my_new_project:
      example:
          materialized: view
```

and profiles.yml is

```
athena_data_warehouse:
  target: awscatalog
  outputs:
    awscatalog:
      type: athena
      database: fy_reporting
      schema: athena_data_warehouse
      s3_staging_dir: athena-data-warehouse
      region_name: eu-west-1
      threads: 8
```

Having removed the id and secret key spec.
